Models/ErrorViewModel.cs
namespace MovieMVCDemo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Movie.cs
namespace MovieMVCDemo.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public int ReleaseYear { get; set; }
    }
}

Models/RickAndMortyCharacter.cs
namespace MovieMVCDemo.Models
{
    public class RickAndMortyCharacter
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public string Species { get; set; }
        public string Image { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MovieMVCDemo.Models;

namespace MovieMVCDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using MovieMVCDemo.Models;
using MovieMVCDemo.ViewModel;

namespace MovieMVCDemo.Controllers
{
    public class MoviesController : Controller
    {
        public IActionResult Index()
        {
            // Simulerar att jag gör API-anrop eller Hämtar data från en databas...
            var movies = new List<Movie>()
            {
                new Movie { Id = 1, Title = "Movie 1", Genre = "Genre 1", ReleaseYear = 2015},
                new Movie { Id = 2, Title = "Movie 2", Genre = "Genre 2", ReleaseYear = 2016},
                new Movie { Id = 3, Title = "Movie 3", Genre = "Genre 3", ReleaseYear = 2017},
            };

            return View(movies);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateMovieVM createMovie)
        {
            if(createMovie == null)
            {
                return View(createMovie);
            }

            // APIet lyckas!

            return RedirectToAction("Index");
        }


        //public IActionResult MovieCards()
        //{
        //    // Simulerar att jag gör API-anrop eller Hämtar data från en databas...
        //    //var movies = new List<Movie>()
        //    //{
        //    //    new Movie { Id = 1, Title = "Movie 1", Genre = "Genre 1", ReleaseYear = 2015},
        //    //    new Movie { Id = 2, Title = "Movie 2", Genre = "Genre 2", ReleaseYear = 2016},
        //    //    new Movie { Id = 3, Title = "Movie 3", Genre = "Genre 3", ReleaseYear = 2017},
        //    //};

        //    return View();
        //}
    }
}

Controllers/RMController.cs
using Microsoft.AspNetCore.Mvc;
using MovieMVCDemo.Models;

namespace MovieMVCDemo.Controllers
{
    public class RMController : Controller
    {
        private readonly HttpClient _client;

        public RMController(IHttpClientFactory clientFactory)
        {
            _client = clientFactory.CreateClient("RickAndMortyApi");
        }

        public async Task<IActionResult> Index()
        {
            var response = await _client.GetAsync("character/1");

            if (response.IsSuccessStatusCode)
            {
                var character = await response.Content.ReadFromJsonAsync<RickAndMortyCharacter>();

                return View(character);
            }

            return View();
        }
    }
}

ViewComponents/LatestMoviesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieMVCDemo.Models;

namespace MovieMVCDemo.ViewComponents
{
    public class LatestMoviesViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var movies = new List<Movie>()
            {
                new Movie { Id = 1, Title = "Movie 1", Genre = "Genre 1", ReleaseYear = 2015},
                new Movie { Id = 2, Title = "Movie 2", Genre = "Genre 2", ReleaseYear = 2016},
                new Movie { Id = 3, Title = "Movie 3", Genre = "Genre 3", ReleaseYear = 2017},
            };

            return View(movies);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Movies/Create.cshtml
@model MovieMVCDemo.ViewModel.CreateMovieVM

<h2>Create Movie</h2>

<form asp-action="Create" method="post">

    <div class="mb-3">
        <label asp-for="Title" class="form-label"></label>
        <input asp-for="Title" class="form-control" />
    </div>

    <div class="mb-3">
        <label asp-for="Genre" class="form-label"></label>
        <input asp-for="Genre" class="form-control" />
    </div>

    <div class="mb-3">
        <label asp-for="ReleaseYear" class="form-label"></label>
        <input asp-for="ReleaseYear" class="form-control"  />
    </div>

    <button type="submit"> Save </button>
</form>

Views/Movies/Index.cshtml
@model List<Movie>

<h1>Movies List</h1>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Genre</th>
            <th scope="col">ReleaseYear<th>
        </tr>
    </thead>
    <tbody>
        @foreach (var movie in Model)
        {
            <tr>
                <td>@movie.Title</td>
                <td>@movie.Genre</td>
                <td>@movie.ReleaseYear</td>
            </tr>
        }
    </tbody>
</table>

Views/Movies/MovieCards.cshtml
<h1>Movie Cards</h1>

@await Component.InvokeAsync("LatestMovies")

@await Component.InvokeAsync("LatestMovies")

@await Component.InvokeAsync("LatestMovies")

Views/RM/Index.cshtml
@model RickAndMortyCharacter

<div>
    @if(Model == null)
    {
        <p>Vi kunde inte hämta karaktären</p>
    }
    else
    {
        <h2>Name: @Model.Name</h2>
        <img src="@Model.Image" style="width:200px;" />
        <p>Status: @Model.Status</p>
        <p>Species: @Model.Species</p>
    }

</div>

Views/Shared/Components/LatestMovies/Default.cshtml
@model List<Movie>

<ul>
    @foreach (var movie in Model)
    {
        <li>
            <div>
                <h4>@movie.Title</h4>
                <span>@movie.ReleaseYear</span>
            </div>
        </li>
    }
</ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieMVCDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieMVCDemo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Aldor Cinema</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MovieMVCDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MovieCard.cshtml
@model Movie

<div>
    <h4>@Model.Title</h4>
    <span>@Model.ReleaseYear</span>
</div>